version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.0.1
      - image: mongo:4.4.1-xenial
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run:
          name: Run tests
          command: npm test
          environment:
            APP_SECRET: TOP_SECRET_APP_PHRASE
            MONGO_URI: mongodb://localhost:27017/test