version: 2.1
jobs:
  build:
    docker:
      - image: node:14
      - image: mongo:4.4.2
    steps:
      - checkout
      - run: yarn --verbose
      - run: yarn lint
      - run:
          name: Run tests
          command: yarn test
          environment:
            APP_SECRET: TOP_SECRET_APP_PHRASE
            MONGO_URI: mongodb://localhost:27017/test